### ISSUE TITLE
Number of bytes in string is wrong

### ISSUE THREAD

**Issue by mauricioszabo** [djblue/nrepl-cljs#1]
Hi, I just saw this line:

https://github.com/djblue/nrepl-cljs/blob/d0307a6bb5146e48e18726081cdf5bb7c0eb9a2e/src/nrepl/bencode.cljs#L63

And I think its wrong: see the official tests (the number should be the number of UTF8 bytes, not the number or chars): https://github.com/nrepl/bencode/blob/master/test/bencode/core_test.clj#L57-L62

If you want, you can use (parts of, or the whole namespace) of my Chlorine implementation for it: https://github.com/mauricioszabo/repl-tooling/blob/master/src/repl_tooling/nrepl/bencode.cljs. It's currently being battle-tested for a lot of scenarios. Or I can open up a PR :smile:

**Comment by djblue** [comment]
@mauricioszabo  I was kinda hoping we could centralize our implementations kinda like https://github.com/nrepl/bencode does for clj. It would be very nice if we could make those cljc files and have a single library 👍 across clj and cljs.

**Comment by mauricioszabo** [comment]
Yes, it would be great! I just didn't do it because my implementation is quite naïve: it is extremely simple, and its slow. It works as a nREPL client, but not as a server because it first creates a big string in memory, then sends to socket...

Even to be used as client, I had to make a change because the decoder was too slow :cold_sweat:.

**Comment by djblue** [comment]
Should be fixed by https://github.com/djblue/nrepl-cljs/commit/6aad45fd482a52a9c5479e5364a5602dbe16f4bc, thanks for the issue!
